version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4005:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
